AUTH_URI: https://accounts.google.com/o/oauth2/auth
CLIENT_SECRET: IlYpBnYc9YKCa09mHbUYkbdm
TOKEN_URI: https://accounts.google.com/o/oauth2/token
CLIENT_EMAIL: 833707550293-o4h3tc5306pvq7j2b607v8q5jnf4a08j@developer.gserviceaccount.com
REDIRECT_URIS: http://localhost:3000/signin/connect
CLIENT_X509_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/901506026811-q0am03i585627ptu5r38o7cpkt8pk98l@developer.gserviceaccount.com
CLIENT_ID: 833707550293-o4h3tc5306pvq7j2b607v8q5jnf4a08j.apps.googleusercontent.com
AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
JAVASCRIPT_ORIGINS: http://localhost:3000
PLUS_LOGIN_SCOPE: https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/tasks https://www.googleapis.com/auth/plus.circles.read